- order-delivery-date-for-woocommerce/class-view-holidays.php
- order-delivery-date-for-woocommerce/css/order-delivery-date.css
- order-delivery-date-for-woocommerce/js/initialize-datepicker.js
- order-delivery-date-for-woocommerce/order_delivery_date.php
A new feature is added which allows to add holidays for delivery calendar. You can add one single holiday once. And all the added holidays will be disable in the calendar with the holiday name given label.
> A new feature of adding holidays.

- order-delivery-date-for-woocommerce/order_delivery_date.php
Version is changed for testing purpose.
> Version 2.8 testing

- order-delivery-date-for-woocommerce/js/orddd-lite-initialize-datepicker.js
- order-delivery-date-for-woocommerce/orddd-lite-process.php
- order-delivery-date-for-woocommerce/orddd-lite-settings.php
- order-delivery-date-for-woocommerce/order_delivery_date.php
You can now add Delivery Date field on the cart page along with checkout page.
> Delivery Date field on Cart page.

- order-delivery-date-for-woocommerce/orddd-lite-settings.php
- order-delivery-date-for-woocommerce/order_delivery_date.php
Validation and Sanitization of the code
> Validation and Sanitization of the code

- order-delivery-date-for-woocommerce/readme.txt
> Live Readme file updated.

- order-delivery-date-for-woocommerce/welcome.php
Plugin is not deleted with a warning.
> Fix one warning

- order-delivery-date-for-woocommerce/order_delivery_date.php
- order-delivery-date-for-woocommerce/readme.txt
= 3.3.1 (28.12.2017) =
*A warning is fixed which was displayed when the plugin is activated.
> Version 3.3.1

- order-delivery-date-for-woocommerce/order_delivery_date.php
- order-delivery-date-for-woocommerce/readme.txt
Updated readme & version number
> Updated readme & version number

- order-delivery-date-for-woocommerce/order_delivery_date.php
- order-delivery-date-for-woocommerce/readme.txt
Extra fields were added on the WooCommerce edit order page with unwanted code
> Version 3.4.2

- order-delivery-date-for-woocommerce/class-view-holidays.php
- order-delivery-date-for-woocommerce/filter.php
- order-delivery-date-for-woocommerce/integration.php
- order-delivery-date-for-woocommerce/orddd-lite-common.php
- order-delivery-date-for-woocommerce/orddd-lite-pro-notices.php
- order-delivery-date-for-woocommerce/orddd-lite-process.php
- order-delivery-date-for-woocommerce/orddd-lite-settings.php
- order-delivery-date-for-woocommerce/order_delivery_date.php
- order-delivery-date-for-woocommerce/uninstall.php
- order-delivery-date-for-woocommerce/welcome.php
Subpackages were not added in the comments
> Changes after review

- order-delivery-date-for-woocommerce/integration.php
> Suggested Changes

- order-delivery-date-for-woocommerce/includes/component/tracking data/class-ts-tracker.php
- order-delivery-date-for-woocommerce/includes/component/tracking data/ts-tracking.php
- order-delivery-date-for-woocommerce/includes/orddd-lite-component.php
- order-delivery-date-for-woocommerce/orddd-lite-settings.php
We have added a new setting under the date settings, which allow admin to opt out from the tracking.
> Admin can opt out from the tracking.

- order-delivery-date-for-woocommerce/includes/component/WooCommerce-Check/ts-woo-active.php
- order-delivery-date-for-woocommerce/includes/component/deactivate-survey-popup/class-ts-deactivation.php
- order-delivery-date-for-woocommerce/includes/component/faq_support/ts-faq-support.php
- order-delivery-date-for-woocommerce/includes/component/pro-notices-in-lite/ts-pro-notices.php
- order-delivery-date-for-woocommerce/includes/component/tracking data/class-ts-tracker.php
- order-delivery-date-for-woocommerce/includes/component/tracking data/ts-tracking.php
- order-delivery-date-for-woocommerce/includes/component/welcome-page/ts-welcome.php
- order-delivery-date-for-woocommerce/includes/orddd-lite-component.php
Added prefix for the boilerplate class name
> Added prefix for the Boilerplate class name

- order-delivery-date-for-woocommerce/includes/component/deactivate-survey-popup/template/ts-deactivate-modal.php
Changed the class name in the template file  of the deactivate popup modal.
> Changed the class name in template file of Deactivate popup modal

- order-delivery-date-for-woocommerce/includes/orddd-lite-component.php
- order-delivery-date-for-woocommerce/order_delivery_date.php
We have applied a change which will show welcome page to only admin users.
For all other users welcome page will not be shown.
> Welcome page for only Admin users

- order-delivery-date-for-woocommerce/js/orddd-lite-initialize-datepicker.js
- order-delivery-date-for-woocommerce/orddd-lite-process.php
A new hook is added which will allow to calculate minimum delivery time on holidays
> A new hook added

- order-delivery-date-for-woocommerce/order_delivery_date.php
- order-delivery-date-for-woocommerce/readme.txt
Changed the version and added changeog in readme.txt
> Version 3.6.1

- order-delivery-date-for-woocommerce/order_delivery_date.php
Version 3.8
Did some code refactoring by removing unwanted code & use of global variables where it was no longer required.
> Version 3.8

- order-delivery-date-for-woocommerce/order_delivery_date.php
Added isset() & removed warning
Fix #189
> Added isset() & removed warning

- order-delivery-date-for-woocommerce/order_delivery_date.php
- order-delivery-date-for-woocommerce/readme.txt
Changelog for Version 3.8.1
1. Fixed a warning that was appearing on Dashboard for some stores after the last update.
2. Removed unwanted code that was being executed on plugin update.
3. Tested with WooCommerce v3.6.1
> Version 3.8.1

- order-delivery-date-for-woocommerce/includes/orddd-lite-common.php
- order-delivery-date-for-woocommerce/includes/orddd-lite-process.php
- order-delivery-date-for-woocommerce/includes/settings/class-view-holidays.php
- order-delivery-date-for-woocommerce/includes/settings/orddd-lite-holidays-settings.php
- order-delivery-date-for-woocommerce/includes/settings/orddd-lite-settings.php
- order-delivery-date-for-woocommerce/js/orddd-lite-initialize-datepicker.js
1. Consecutive Holidays can now be added in one time on the Holidays Tab. 
2. Also, the holiday dates can now be added for recurring year also.
> Consecutive Holidays along with Recurring Year Holidays.

- order-delivery-date-for-woocommerce/css/order-delivery-date.css
- order-delivery-date-for-woocommerce/includes/settings/orddd-lite-appearance-settings.php
- order-delivery-date-for-woocommerce/includes/settings/orddd-lite-calendar-sync-settings.php
- order-delivery-date-for-woocommerce/includes/settings/orddd-lite-date-settings.php
- order-delivery-date-for-woocommerce/includes/settings/orddd-lite-settings.php
- order-delivery-date-for-woocommerce/includes/settings/orddd-lite-shipping-days-settings.php
- order-delivery-date-for-woocommerce/order_delivery_date.php
Added some of the PRO settings which are mostly used by clients like Custom Delivery Settings, Google Calendar Sync is added as disabled settings in the Lite version.
> Added some of the PRO settings in lite version.

- order-delivery-date-for-woocommerce/order_delivery_date.php
- order-delivery-date-for-woocommerce/readme.txt
Readme File updated for 3.9 version
> Readme File updated for 3.9 version

- order-delivery-date-for-woocommerce/order_delivery_date.php
- order-delivery-date-for-woocommerce/readme.txt
Changes in code to make the plugin compliant as per WPCS rules.
> Version 3.10

- order-delivery-date-for-woocommerce/readme.txt
Updating readme.txt with the 7 new plugins & removing plugins of Arconix & some of Tyche free plugins too.
> Updating readme.txt with the 7 new plugins & removing unwanted plugins

- order-delivery-date-for-woocommerce/readme.txt
> Updating tags

- order-delivery-date-for-woocommerce/readme.txt
Updating readme Stable tag & Requires PHP tag
> Updating readme Stable tag & Requires PHP tag

- order-delivery-date-for-woocommerce/readme.txt
Removing Addons & instead putting the differences text there
> Removing Addons & instead putting the differences text there

- order-delivery-date-for-woocommerce/readme.txt
Removing Addons text & replacing it with Differences heading
> Removing Addons text & replacing it with Differences heading

- order-delivery-date-for-woocommerce/readme.txt
Moving Difference FAQ as first one instead of last one.
> Moving Difference FAQ as first one instead of last one.

- order-delivery-date-for-woocommerce/readme.txt
> Added remaining 7 pro plugins

- order-delivery-date-for-woocommerce/order_delivery_date.php
- order-delivery-date-for-woocommerce/readme.txt
Updated compatibility with WC 4.0.0
> Version 3.10.1

- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-additional-settings.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-appearance-settings.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-date-settings.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-delivery-days-settings.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-filter.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-settings.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-time-settings.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-time-slot-settings.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-view-disable-time-slots.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-view-specific-table.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-view-time-slots.php
Added a tab for General settings and created sections like in pro version with the settings available only in pro disabled
> Add settings section in the admin side

- order-delivery-date-for-woocommerce/includes/class-orddd-lite-common.php
- order-delivery-date-for-woocommerce/includes/class-orddd-lite-process.php
- order-delivery-date-for-woocommerce/order_delivery_date.php
Added the functionality for time slots with lockout & time slot charges.
> Add the functionality for time slots

- order-delivery-date-for-woocommerce/css/jquery.datepick.css
- order-delivery-date-for-woocommerce/css/order-delivery-date.css
- order-delivery-date-for-woocommerce/js/jquery.datepick.js
- order-delivery-date-for-woocommerce/js/orddd-lite-initialize-datepicker.js
Added the datepick library for the block time slot feature and modified the js & css files for the time slot feature
[do-not-scan]
> Add the modified js & css files for time slot feature

- order-delivery-date-for-woocommerce/includes/class-orddd-lite-process.php
- order-delivery-date-for-woocommerce/js/orddd-lite-initialize-datepicker.js
The time slot charges were not applied correctly when the time slots were open ended or when the auto populate time slot setting was enabled.
Also Fixes #253
> Fix #254:The time slot charges were not applied correclty

- order-delivery-date-for-woocommerce/includes/class-orddd-lite-common.php
- order-delivery-date-for-woocommerce/includes/class-orddd-lite-process.php
- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-time-slot-settings.php
- order-delivery-date-for-woocommerce/order_delivery_date.php
When the order status changed from cancelled to processing, the lockout was not getting added again. Also fixed the console error coming when the date lockout& time lockout both were set.
Also Fixes #260 
Fixes #257
> The lockout was not added when the order status changed from cancelled to processing

- order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-holidays-settings.php
When the holidays were saved for the first time, there was a warning coming
> Fix #265:fixed the warning coming while saving holidays

- order-delivery-date-for-woocommerce/order_delivery_date.php
- order-delivery-date-for-woocommerce/readme.txt
Version 3.11.0
* Feature - Ability to add time slots for weekdays. You can now add time slots with maximum order deliveries per time slot, time slot charges.
* Feature - Ability to block time slots for dates or weekdays.
* Fix - Fixed the error coming with WordPress 5.5.
> Version 3.11.0

- js/orddd-lite-initialize-datepicker.js
- order_delivery_date.php
A console error was displayed for undefined function with selectWoo with a few themes. 
Fix #284
> Fixed the console error coming due to selectWoo

- order_delivery_date.php
- readme.txt
> Version 3.11.3

- includes/class-orddd-lite-common.php
When some of the weekdays were disabled then the MDT was not getting calculated correctly.
> Fix #287:The MDT was not getting calculated correctly when weekdays were disabled

- order_delivery_date.php
- readme.txt
> Version 3.11.4

- readme.txt
> Updated readme file for WP5.6

- readme.txt
Updated the screenshot labels on the plugin page for the new screenshots.
> Update the captions of the new screenshots added on plugin page

- includes/class-orddd-lite-common.php
> Fix #309: Fixed the debug log error

- order_delivery_date.php
- readme.txt
> Version 3.11.5

- includes/settings/class-orddd-lite-date-settings.php
We can now set decimals as MDT in the settings.
> Fix #277: Decimals could not be set in the MDT

- order_delivery_date.php
- readme.txt
> Version 3.11.6

- order_delivery_date.php
- readme.txt
> Version 3.11.7

- order_delivery_date.php
- readme.txt
> Version 3.11.8

- order_delivery_date.php
- readme.txt
> Version 3.11.9

- readme.txt
Update readme for compatibility with WP 5.7
> Update readme for compatibility with WP 5.7

- includes/class-orddd-lite-process.php
In this commit, I have fixed this. Fix #335
> Fixed the issue of maximum order deliveries per time slot is not working.

- includes/class-orddd-lite-process.php
- js/orddd-lite-initialize-datepicker.js
In this commit, I have fixed this.  Fix #337
> Fixed the issue of number of dates to choose do not include holiday days.

- includes/settings/class-orddd-lite-filter.php
In this commit, I have added this.
> Added the delivery details in edit order page and view order popup.

- includes/class-orddd-lite-process.php
In this commit, I have fixed this issue. Fix #338
> Fixed the issue of allowing to enter past delivery dates

- order_delivery_date.php
- readme.txt
> Version 3.12.0

- order_delivery_date.php
- readme.txt
updated compatibility for WP5.8, WC 5.5
> updated compatibility for WP5.8, WC 5.5

- emails/class-orddd-lite-email-update-date.php
- includes/class-orddd-lite-admin-delivery.php
- includes/class-orddd-lite-email-manager.php
- includes/class-orddd-lite-process.php
- js/orddd-lite-initialize-datepicker.js
- order_delivery_date.php
- templates/emails/admin-update-date.php
- templates/emails/plain/admin-update-date.php
In this commit, I have fixed this. Fix #348
> Added metabox for edit delivery date and time in edit order page

- includes/class-orddd-lite-integration.php
In this commit, I have fixed the issue. Fix #339
> Fixed the issue of not showing time slots in invoice pdf

- includes/class-orddd-lite-process.php
- js/orddd-lite-initialize-datepicker.js
- order_delivery_date.php
In this commit, I have fixed this. Fix #311
> Fixed the issue of not applying delivery charges for time-slots

- includes/class-orddd-lite-admin-delivery.php
- includes/class-orddd-lite-integration.php
In this commit, I have fixed the issue. fix #v3.13.0-testing-fix
> fixed the issues found in testing

- templates/emails/admin-update-date.php
In this commit, I have fixed this.
> Fixed some minor issue

- order_delivery_date.php
- readme.txt
Uploading changes for version-3.13.0
> version-3.13.0

- includes/class-orddd-lite-process.php
- includes/settings/class-orddd-lite-additional-settings.php
- includes/settings/class-orddd-lite-appearance-settings.php
- includes/settings/class-orddd-lite-settings.php
- js/orddd-lite-initialize-datepicker.js
- order_delivery_date.php
In this commit, I have fixed this issue.
> Added colors code for calendar

- css/datepicker.css
- js/accessibility.js
- order_delivery_date.php
In this commit, I have added accessibility.js file for screen reader.
> Added accessibility for screen reader

- order_delivery_date.php
In this commit, I have fixed this issue. Fix #361
> fixed the warning of error_log

- includes/settings/class-orddd-lite-appearance-settings.php
In this commit, I have fixed this issue. Fix #363
> Fixed the error of color code setting

- order_delivery_date.php
- readme.txt
- uninstall.php
Uploading changes for version-3.14.0
> version-3.14.0

- js/orddd-bulk-time-slots.js
In this commit, I have fixed this issue. Fix #372
> fixed the issue of not showing time-slots in same format

- includes/settings/class-orddd-lite-settings.php
In this commit, I have fix this issue. Fix #373
> Fixed the issue of URI to large error while deleting bulk time-slots

- js/orddd-lite-initialize-datepicker.js
In this commit, I have fixed this issue. Fix #374
> Fixed the issue of showing Available on past dates

- includes/settings/class-orddd-lite-time-slot-settings.php
In this commit, I have fixed the issue. Fix #375
> Fixed the error-log warnings

- order_delivery_date.php
- readme.txt
uploading changes for v-3.15.0
> version v-3.15.0

- js/orddd-lite-initialize-datepicker.js
In this commit, I have fixed this issue. Fix #381
> Fixed the issue of blocked dates

- order_delivery_date.php
- readme.txt
uploading changes of version v-3.15.1
> version v-3.15.1

- languages/order-delivery-date.pot
- templates/emails/admin-update-date.php
In this commit, I have fixed the issue. Fix #357
> Updated .pot file for missing translations

- includes/settings/class-orddd-lite-settings.php
In this commit, I have fixed this issue. Fix #345
> Fixed the issue of showing unwanted nbsp

- includes/settings/class-orddd-lite-appearance-settings.php
In this commit, I have fixed this issue. Fix #63
> Fixed the issue of not showing first day as selected in Preview

- includes/class-orddd-lite-admin-delivery.php
- includes/class-orddd-lite-common.php
- includes/class-orddd-lite-process.php
- js/accessibility.js
- js/orddd-lite-initialize-datepicker.js
- order_delivery_date.php
- templates/orddd-lite-admin-datepicker.php
- templates/orddd-lite-datepicker-template.php
In this commit, I have added hidden variables with JS localize variables and added templates for delivery date and time.
> Changed hidden variables with JS localize variables and added templates for delivery date and time

- readme.txt
Have changed the content on the wp.org repo page.
> Description updated on wp.org

- includes/settings/class-orddd-lite-appearance-settings.php
In this commit, I have fixed the issue, Fix #398
> Fixed the issue of not showing selected First day of week.

- includes/settings/class-orddd-lite-settings.php
In this commit, I have added a disabled attr to submit button to make them not clickable. Fix #396
> disabled submit button for section which are not available to use in lite version

- includes/settings/class-orddd-lite-settings.php
- includes/settings/class-orddd-lite-shipping-days-settings.php
- languages/order-delivery-date.pot
In this commit, I have changed the texts. Fix #394
> Changed Business Days Settings texts same as pro plugin

- includes/settings/class-orddd-lite-settings.php
In this commit, I have changed the text. Fix #392
> Changed the Example text for "Apply Minimum Delivery Time for non working weekdays"

- includes/class-orddd-lite-common.php
- includes/class-orddd-lite-process.php
- js/orddd-lite-initialize-datepicker.js
In this issue, I have fixed this. Fix #404
> Fixed the issue of not working Partially booked option

- includes/class-orddd-lite-process.php
- templates/orddd-lite-admin-datepicker.php
In this commit, I have fixed the issue, Fix #357
> Fixed the issue of not translating string in Edit order page

- includes/class-orddd-lite-common.php
In this commit, I have fixed this. Fix #397
> fixed the issue of not showing dates in selected datepicker language on order received page

- includes/orddd-lite-component.php
In this commit, I have changed the text. Fix #406
> Changed FAQ content for Time-slots

- order_delivery_date.php
- readme.txt
uploading changes for v-3.16.0
> version v-3.16.0

- order_delivery_date.php
- readme.txt
> Version 3.16.1

- includes/class-orddd-lite-integration.php
> Fixed display of time slot in print invoice & delivery note plugin

- includes/class-orddd-lite-admin-delivery.php
- js/orddd-lite-initialize-datepicker.js
[do-not-scan]
Change delivery date format before saving to save it correctly.
> Fix #415, Fix #366

- order_delivery_date.php
> Release 3.17.1

- includes/class-orddd-lite-process.php
- js/orddd-lite-initialize-datepicker.js
Return if the plugin is not being used/ delivery date is disabled.
[do-not-scan]
> Fix #446, #450

- order_delivery_date.php
- readme.txt
> Version 3.17.2

- includes/orddd-lite-config.php
Want to see date format d-m-Y also
> Add date format d-m-Y

- order_delivery_date.php
- readme.txt
> changes for v3.18.0

- includes/class-orddd-lite-admin-delivery.php
- includes/class-orddd-lite-common.php
- includes/class-orddd-lite-process.php
- includes/settings/class-orddd-lite-filter.php
- order_delivery_date.php
> HPOS updates

- includes/component/tracking-data/ts-tracking.php
> changed the cron event

- includes/class-orddd-lite-common.php
> Fixed deprecated notice

- order_delivery_date.php
- readme.txt
> uploading changes for version-3.19.0

- includes/settings/class-orddd-lite-additional-settings.php
- includes/settings/class-orddd-lite-filter.php
- js/orddd-lite-shop-order.js
- languages/order-delivery-date.pot
- order_delivery_date.php
Added a filter dropdowon WooCOmmerce orders page.
- Filter by months
- Filter by custom date range
- Filter by today/tomorrow
[do-not-scan]
> Add order filter feature

- order_delivery_date.php
> version 3.20.0

- readme.txt
Updated the changelog for 3.20.0
[do-not-scan]
> Update readme.txt file with changelog

- readme.txt
> update readme with content changes

- includes/settings/class-orddd-lite-filter.php
A vulnerability issue was found on the orders page when filtering the orders, the values were not escaped properly.
Fix #500 
[do-not-scan]
> Fix the vulnerability issue

- order_delivery_date.php
- readme.txt
> Version 3.20.1

- includes/settings/class-orddd-lite-settings.php
Changed the labels for settings sections
> Changed the labels for the settings

- languages/order-delivery-date.pot
- order_delivery_date.php
- readme.txt
> Version 3.20.2

- includes/component/plugin-tracking/class-tyche-plugin-tracking.php
- order_delivery_date.php
- readme.txt
> Updated Version into 3.21.1

- includes/class-orddd-lite-common.php
Fixed fatal error when restore post from admin side. Fix #537
> Fixed fatal error when restore post

- includes/class-orddd-lite-process.php
"As soon as possible" option appearing first in the dropdown list. Fix #538
> ASAP option displaying first

- js/orddd-lite-initialize-datepicker.js
- order_delivery_date.php
Fixed Uncaught Missing instance data for this datepicker js error from console. Fix #536, Fix #531
> Fixed js error from console

- order_delivery_date.php
- readme.txt
> Updated version into 3.22.0

- includes/component/upgrade-to-pro/ts-upgrade-to-pro.php
I have updated the notice text according to [this](https://docs.google.com/document/d/1-dIfaXhAY1n-fVsvpDkji4gSH6G0tBRSMckx0mPZCDE/edit?disco=AAABVOtyqcc) discussion in BRD.
> Trial Changes continue

- includes/component/upgrade-to-pro/ts-upgrade-to-pro.php
- order_delivery_date.php
- readme.txt
> Version 3.23.0

- includes/component/plugin-deactivation/class-tyche-plugin-deactivation.php
- order_delivery_date.php
- readme.txt
Fixed deactivation survey changes.
> Fixed deactivation survey changes

- includes/class-orddd-lite-common.php
- includes/component/plugin-deactivation/class-tyche-plugin-deactivation.php
Fixed debug log error when trash the order Fix #568
> Fixed log error

- includes/class-orddd-lite-common.php
- order_delivery_date.php
- readme.txt
Fixed compatibility with Fluid Checkout for WooCommerce - Lite plugin. Fix #560
> Fixed combability with Fluid Checkout for WooCommerce - Lite plugin

- order_delivery_date.php
- readme.txt
> Updated version into 3.24.0

- includes/class-orddd-lite-common.php
- order_delivery_date.php
Fixed Issue with the Sorting in admin column Fix #578
> Fixed delivery column sorting issue

- order_delivery_date.php
- readme.txt
> Version 3.25.0

- order_delivery_date.php
- readme.txt
> Version 3.26.0

- order_delivery_date.php
- readme.txt
> Version 3.26.1

- changelog.txt
- includes/class-orddd-lite-admin-delivery.php
- includes/class-orddd-lite-common.php
- includes/class-orddd-lite-process.php
- includes/component/faq-support/templates/faq-page/faq-page.php
- includes/component/faq-support/ts-faq-support.php
- includes/component/upgrade-to-pro/templates/upgrade-to-pro-page/upgrade-to-pro-modal.php
- includes/component/woocommerce-check/ts-woo-active.php
- includes/integrations/wc-blocks/class-orddd-lite-delivery-blocks.php
- includes/integrations/wc-blocks/order-delivery-date-block.php
- includes/settings/class-orddd-lite-filter.php
- includes/settings/class-orddd-lite-settings.php
- includes/settings/class-orddd-lite-view-holidays-table.php
- order_delivery_date.php
- templates/orddd-lite-delivery-schedule-html.php
- templates/orddd-lite-integrations-html.php
"This PR includes WooMarketplace-related changes and fixes for QIT errors."
> Fix Woo market place errors

- includes/component/upgrade-to-pro/ts-upgrade-to-pro.php
Added a admin notice to display now orddd menu display under the woocommerce.
> Added a notice for orddd main menu

- changelog.txt
- order_delivery_date.php
- readme.txt
> Version 4.0.0

- changelog.txt
- order_delivery_date.php
- readme.txt
> Version 4.1.0
