TycheSoftwares/order-delivery-date-for-woocommerce

order-delivery-date-for-woocommerce/order_delivery_date.php
* Feature - From now you can set holidays on the dates you do not deliver products under Holidays tab. Selected holidays will be disabled for delivery in the delivery calendar on the checkout page.
* Feature - A new checkbox named 'Auto-populate first available Delivery date' is added in Date Settings tab. If this checkbox is enabled then the first available Delivery Date will be Auto-populated in the Delivery Date field on the Checkout Page.
* Feature - A new checkbox named 'Apply Minimum Delivery Time for non-working weekdays' is added under Date Settings tab. If this checkbox is checked then the Minimum Delivery Time (in hours) will be calculated on the non-working days which are unchecked under Delivery Days. If the checkbox is unchecked then the minimum delivery time will be …
=> Version 2.8 final copy

order-delivery-date-for-woocommerce/order_delivery_date.php, order-delivery-date-for-woocommerce/readme.txt
= 2.9 =
* Fix - Warnings were displayed on the Order Received page with WooCommerce version 3.0.0. This is fixed now.
=> Version 2.9

order-delivery-date-for-woocommerce/orddd-lite-pro-notices.php, order-delivery-date-for-woocommerce/order_delivery_date.php
We have added 5 notices at the admin side. It will display after 15 days, 22 days, 30 days and 37 days after the first notice has been ignored.
If The Order Delivery Date Pro for WooCommerce plugin is activated then none of the notices will be shown.
In Second and Fifth notice that is on 15th day and on 37th day, the notice of 'Post Delivery Product Reviews' addon will be displayed.
If the addon is active then the next notice which is AC lite notice will be displayed for the second notice.
In third notice that is 22 days, we are showing it for AC lite, so AC Pro is activated then we wil not display the same notice.
On dismissable of 3rd notice, again Orddd Pro notice will be shown.
=> Admin notices for pro version and for other plugins

order-delivery-date-for-woocommerce/order_delivery_date.php, order-delivery-date-for-woocommerce/readme.txt
= 3.1 (19.07.2017) =
* You can add the Delivery Date field on the WooCommerce Cart page along with the Checkout page. A checkbox is added for this under Appearance tab.
* The selected Delivery Date will be retained until the order is placed.
=> Version 3.1

order-delivery-date-for-woocommerce/order_delivery_date.php, order-delivery-date-for-woocommerce/readme.txt
= 3.2 (06.09.2017) =
* A new language Persian is added for the calendar. Now you can set your Delivery Calendar in the Persian language on the Checkout Page.
* Some strings were not translated using the .po files. This is fixed now.
=> Version 3.2

order-delivery-date-for-woocommerce/order_delivery_date.php, order-delivery-date-for-woocommerce/readme.txt
= 3.3 (28.12.2017) =
* The delivery date field label was not coming properly on the checkout page. This is fixed now.
* Delivery weekdays were not getting deleted when the plugin is deleted. This is fixed now.
* Some errors in the debug.log file are fixed.
=> Version 3.3

order-delivery-date-for-woocommerce/includes/component/tracking data/class-ts-tracker.php, order-delivery-date-for-woocommerce/orddd-lite-common.php
When select No for the tracking we send the admin email along with some delivery data.
Now, we do capture admin email and do not send any delivery data.
=> We do not track any data when selected No for tracking

order-delivery-date-for-woocommerce/order_delivery_date.php, order-delivery-date-for-woocommerce/readme.txt
= 3.5 (23.05.2018) =
* The plugin is now GDPR compliant.
* Delivery Date & Time for the orders will now be exported to the User's Personal Data from the Tools -> Export Personal Data menu.
* A warning was displayed on the checkout page when Minimum delivery time is set to blank. This is fixed now.
* Some notices are fixed in debug.log file.
=> Version 3.5

order-delivery-date-for-woocommerce/order_delivery_date.php, order-delivery-date-for-woocommerce/readme.txt
= 3.6 (03.07.2018) =
There are some enhancements and some bug fixes in this update which are mentioned below:
* Enhancements:
* A new dismissible notice is added in the WordPress admin, which provides an option to allow usage tracking of the non-sensitive data of our plugin from the website.
* A new FAQ & Support menu is added to Order Delivery Date menu in admin dashboard which lists the top 10 frequently asked questions. This helps you to resolve your queries in a more faster way if they are already been answered or you can simply contact our Support team with the contact details provided.
* A Welcome page is added which will be shown on installation or updating of the plugin. It explains some exciting features or some new features in brief.
* A survey is added on deactivation of the …
=> Version 3.6

order-delivery-date-for-woocommerce/order_delivery_date.php, order-delivery-date-for-woocommerce/readme.txt
There are some bug fixes in this update:
* Incorrect delivery date was preselected in the delivery calendar on the checkout page when the current date is set as a holiday. This is fixed now.
* Preview calendar width was not coming proper on the Appearance link in Order Delivery Date -> Settings when the Eggplant calendar theme was selected. This is fixed now.
* Incorrect delivery date was preselected in the delivery calendar on the checkout page when the available dates have booked dates in between along with some weekdays disabled. This is fixed now.
* Incorrect delivery date was preselected on the checkout page due to the delivery date being stored in the session. This is fixed now.
* Width of the Delivery date field on the cart page was not proper. This is fixed now.
* On changing the …
=> Version 3.7

order-delivery-date-for-woocommerce/order_delivery_date.php
3.9 (23.07.2019)
* Feature - You can now set a range of dates as holidays.
* Feature - You can now block the holidays for future years too. A checkbox named ‘Allow Recurring’ is added which if checked while adding holidays, it will disable the dates for all years in the calendar.
* Bug Fix -  Delivery Date calendar was not working on the checkout page with the Prohauz child theme. This is fixed now.
* Bug Fix - Number of dates available in the calendar was one less than the value set for the "Number of Dates to choose" option. This is fixed now.
=> Version 3.9

order-delivery-date-for-woocommerce/includes/component/tracking-data/assets/js/dismiss-notice.js, order-delivery-date-for-woocommerce/js/dismiss-notice.js
A js error was coming in WP 5.5 for an undefined variable. 
[do-not-scan]
=> Fix #241: fix the error coming in WP 5.5

order-delivery-date-for-woocommerce/includes/orddd-lite-config.php, order-delivery-date-for-woocommerce/uninstall.php
Added a default value for time slot label and fixed the error for time slot formats. And delete the options while deleting the plugin.
Also Fixes #249
=> Fix #2481:Add the default value for time slot label

order-delivery-date-for-woocommerce/includes/class-orddd-lite-common.php, order-delivery-date-for-woocommerce/includes/class-orddd-lite-process.php, order-delivery-date-for-woocommerce/order_delivery_date.php
When the time slot label was set to blank at that time the time slot was not displayed in the email.
=> Fix #250:The time slot was not displayed in email when the label was blank

order-delivery-date-for-woocommerce/includes/class-orddd-lite-common.php
'As soon as possible' was not displayed on the checkout page time slot dropdown.
=> Fix #251:The ASAP option was not displayed in the dropdown

order-delivery-date-for-woocommerce/includes/class-orddd-lite-common.php, order-delivery-date-for-woocommerce/js/orddd-lite-initialize-datepicker.js
When the order status was changed from processing to failed or cancelled, the lockout was not released when the time slot label was blank.
=> Fix #259:Lockout was not released when the time slot label was blank

order-delivery-date-for-woocommerce/includes/settings/class-orddd-lite-settings.php, order-delivery-date-for-woocommerce/order_delivery_date.php
Time slot label was coming blank when plugin was activated for the first time
=> Fix #248:Time slot label was coming blank on fresh install

order-delivery-date-for-woocommerce/includes/orddd-lite-config.php
When the field placement was selected as 'Between Your Order & Payment Section', the date field was still placed in the Billing section.
=> Fix #269:The date field placement was incorrect

order-delivery-date-for-woocommerce/includes/class-orddd-lite-process.php, order-delivery-date-for-woocommerce/order_delivery_date.php
Array word was displayed in the emails when the time slot label was not saved in the database after the update
=> Fix #271: Array word was displayed in the emails

order-delivery-date-for-woocommerce/order_delivery_date.php, order-delivery-date-for-woocommerce/readme.txt
* Fix - 'Array' word was being displayed in the order emails.
* Fix - The delivery date field was not placed correctly when the setting 'Field placement on the Checkout page' was set to 'Between Your Order & Payment Section'.
=> Version 3.11.1

includes/class-orddd-lite-common.php, includes/class-orddd-lite-process.php, js/orddd-lite-initialize-datepicker.js
The 'Apply Minimum Delivery Time for non working weekdays' setting was not working correctly. The disabled weekdays were not considered when calculating the min date.
Fix #274
=> Minimum delivery time was not applied on disabled days even if the setting was enabled

includes/class-orddd-lite-common.php
All the timeslots for a date were displayed even if the MDT was applied and they should have been disabled.
=> Fix #279:MDT was not applied on time slots

js/orddd-lite-initialize-datepicker.js
Wrong date was being auto-populated on the calendar when some of the weekdays were disabled.
=> Fix #280: Wrong date was being auto-populated

order_delivery_date.php, readme.txt
* Fix - The first available date was coming wrong when the 'Apply Minimum Delivery Time for non working weekdays' setting was enabled.
* Fix - Minimum Delivery time was not being calculated on the time slots.
* Fix - Wrong date was being auto-populated on checkout page.
=> Version 3.11.2

includes/settings/class-orddd-lite-settings.php
The auto populate setting was not getting disabled when the settings were saved.
=> Fix #285: The auto-populate setting was not getting disabled

js/orddd-lite-initialize-datepicker.js, readme.txt
When the current day was enabled in the weekdays, the checkout page was becoming unresponsive due to an infinite loop.
Also updated readme.txt
=> Fix #286:The checkout page hanged when current day was selected

js/orddd-lite-initialize-datepicker.js
When we translates page from Google Chrome, delivery date was showing as "NaN Undefined, NaN" 
[do-not-scan]
=> Fix #196:NaN was coming for the date when translated in the google chrome

includes/settings/class-orddd-lite-holidays-settings.php, includes/settings/class-orddd-lite-settings.php
When we clicked on save settings without entering any values, then all the holidays were getting deleted.
Fix #300
=> Fix #300:The holidays were getting deleted when empty settings were saved

order_delivery_date.php
A fatal error was displayed when the plugin was installed with PHP 7.3
=> Fix #312:Fatal error was coming when installing plugin with PHP 7.3

js/orddd-lite-initialize-datepicker.js
When a holiday was added in the settings, one more extra day was disabled when MDT was calculated.
=> Fix #302:MDT was not calculated correctly when a holiday was added

js/orddd-lite-initialize-datepicker.js
When a holiday was set with MDT then wrong date was auto populating on checkout
=> Fix #318:Wrong date was auto populating when holiday was set with mdt

includes/class-orddd-lite-process.php, js/orddd-lite-initialize-datepicker.js
The date was not saved in the session when the cart page setting was disabled. Now the date will be saved and the session date will be populated on load of the page.
[do-not-scan]
=> Fix #303: The date was not saved in the session on checkout

js/orddd-lite-initialize-datepicker.js
The time slot field was disabled even when the date was auto-populated on cart & checkout page.
[do-not-scan]
=> Fix #324:Time slot was not autopopulating when the date was auto-populated

order_delivery_date.php
In this commit, I have fixed it. Fix #328
This issue is happening due to `orddd-lite-initialize-datepicker.js` file loading earlier than the regional datepicker file so it only showing the date in English when the page loads.
=> Fixed the issue of not getting translating auto populate date

includes/class-orddd-lite-admin-delivery.php, js/orddd-lite-initialize-datepicker.js
In this commit, I have fixed this issue. Fix #365, #366
There is one jQuery error and due to that error, the click event of an update button is not firing and hence it is not saving the delivery date as mentioned in issue #366 so both the issues will be fixed with this PR.
=> Fixed the issue of not showing date in edit-order

css/order-delivery-date.css, includes/settings/class-orddd-lite-settings.php
In this commit, I have fixed this issue. Fix #395
=> Fixed the extra space issue between Specific Delivery Date Text and Specific delivery dates setup box.

order_delivery_date.php, readme.txt
Fix cut-off time error for 'Select time slot' and 'Timeslots not available.
[do-not-scan]
=> Version 3.17.3

includes/class-orddd-lite-common.php
When the order had a time range with date from pro version, the date was displayed as '1 January, 1970' and  it was being included in the search results.
Fix #494 
[do-not-scan]
=> Incorrect date was displayed for a order

includes/class-orddd-lite-common.php
Fixed some strings are not translated when ORDD Lite is active. Fix #545
=> Fixed string translation issue

includes/component/plugin-tracking/js/tyche-dismiss-tracking-notice.js, includes/component/upgrade-to-pro/ts-upgrade-to-pro.php
In this commit, I have added code to allow the store admin to dismiss the notices added during the trial version changes. These notices will be displayed only on the odd plugin settings page.
=> Notice Dismiss Changes

includes/component/plugin-tracking/ts-tracking.php, order_delivery_date.php
In this commit, I have fixed the following issues
1. The Upgrade to Pro submenu was not coming
2. The tyche-dismiss-tracking-notice.js file was loaded with a static version number hence the caching issue.
=> Fixes for 3.25.0
